export enum apiRoutes {
  LOGIN = '/auth/login',
  SIGNUP = '/auth/register',
  SIGNOUT = '/auth/signout',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_USER = '/auth',
  FETCH_USERS = '/users',
  USERS_PREFIX = '/users',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  UPLOAD_PRODUCT_IMAGE = '/products/upload',
  GET_AVATAR_IMAGE = '/users/get/image',
  PRODUCTS_PREFIX = '/products',
  ROLES_PREFIX = '/roles',
  ORDERS_PREFIX = '/orders',
  PERMISSIONS_PREFIX = '/permissions',
}
